# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Cvault < Formula
  desc "cvault"
  homepage "https://github.com/getclair/cvault"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/getclair/cvault/releases/download/v1.0.9/cvault_1.0.9_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "74d1d4df9ba6626f49e5b2749866468d1f583a56053625aa71f000573628519b"

      def install
        bin.install "cvault"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/getclair/cvault/releases/download/v1.0.9/cvault_1.0.9_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3dbe58e80b9aa258b2f00adb5a90b09972c47c914f05d4e0e08b4dbcb96bc223"

      def install
        bin.install "cvault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/getclair/cvault/releases/download/v1.0.9/cvault_1.0.9_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a2ec77b93309e84d4b39d8ce6a3db3d18906eb05bb630a4b1fe323bacf9a9698"

      def install
        bin.install "cvault"
      end
    end
  end
end
